name: Code Quality Checks

on:
  workflow_call:

jobs:
  lint_check:
    name: Android Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Setup Android Environment and permission
        uses: ./.github/actions/setup-android
        with:
          java-version: '17'

      - name: Check Code Quality lINT
        uses: ./.github/actions/check-code/lint

  klint_check:
    name: Android Klint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Setup Android Environment and permission
        uses: ./.github/actions/setup-android
        with:
          java-version: '17'

      - name: Check Code Quality Klint
        uses: ./.github/actions/check-code/ktlint